### ISSUE TITLE
"caffe.LayerParameter" has no field named "patch_transformer_param"

### ISSUE THREAD

**Issue by Bkmz21** [mitmul/ssai#2]
Hi,
I'm trying to run training model for your scripts.
But i'm getting an error.
What could be the reason?

Best regards,
Ilya

start learning models/Mnih_CNN_Buildings
kalinovskiy@kalinovskiy-virtual-machine:/project/ssai-master$ I1013 02:18:28.541991 15748 caffe.cpp:117] Use CPU.
I1013 02:18:28.542275 15748 caffe.cpp:121] Starting Optimization
I1013 02:18:28.542351 15748 solver.cpp:32] Initializing solver from parameters: 
test_iter: 100
test_interval: 1000
base_lr: 0.0005
display: 100
max_iter: 400000
lr_policy: "step"
gamma: 0.1
momentum: 0.9
weight_decay: 0.0005
stepsize: 100000
snapshot: 10000
snapshot_prefix: "snapshots/Mnih_CNN_Buildings"
solver_mode: CPU
device_id: 2
random_seed: 1701
net: "train_test.prototxt"
solver_type: SGD
I1013 02:18:28.542444 15748 solver.cpp:70] Creating training net from net file: train_test.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 53:27: Message type "caffe.LayerParameter" has no field named "patch_transformer_param".
F1013 02:18:28.542604 15748 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: train_test.prototxt
**\* Check failure stack trace: ***
    @     0x7fd8bafc8ea4  (unknown)
    @     0x7fd8bafc8deb  (unknown)
    @     0x7fd8bafc87bf  (unknown)
    @     0x7fd8bafcba35  (unknown)
    @     0x7fd8bb3df941  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7fd8bb4036e2  caffe::Solver<>::InitTrainNet()
    @     0x7fd8bb404760  caffe::Solver<>::Init()
    @     0x7fd8bb404946  caffe::Solver<>::Solver()
    @           0x40dd50  caffe::GetSolver<>()
    @           0x406e22  train()
    @           0x40472b  main
    @     0x7fd8ba4c8a40  (unknown)
    @           0x404d79  _start
    @              (nil)  (unknown)

**Comment by mitmul** [comment]
Did you build 'ssai' branch of my modified caffe?
https://github.com/mitmul/caffe/tree/ssai

**Comment by Bkmz21** [comment]
No
Thanks!
Can I use mask for buildings of another color (not red)?

**Comment by mitmul** [comment]
What do you mean? The output of the model "Mnih_CNN_Buildings" that you tried to train constructs a single channel image.

**Comment by Bkmz21** [comment]
I'm mean the format of source data.
map-data is binarized when generating labels and not tied to color?

**Comment by mitmul** [comment]
If you use the model that outputs single channel results, the training label patches should be also single channel images.
